[tool.black]
line-length = 79
target-version = ['py39']
include='.py$'
exclude = '(\.venv|venv|\.git|\.pytest_cache|\.tox|.*egg)'

[tool.isort]
py_version = 37
line_length = 79
length_sort = true
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true